# Generated by Django 6.0.3 on 2026-04-04 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrabajoManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('precio_estimado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('precio_final', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('estado', models.CharField(choices=[('consulta', 'Consulta recibida'), ('cotizado', 'Cotizado'), ('en_proceso', 'En proceso'), ('entregado', 'Entregado')], default='consulta', max_length=20)),
                ('whatsapp_link', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.usuario')),
            ],
            options={
                'verbose_name': 'Trabajo Manual',
                'verbose_name_plural': 'Trabajos Manuales',
            },
        ),
        migrations.CreateModel(
            name='TrabajoManualFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='trabajos/')),
                ('orden', models.PositiveIntegerField(default=0)),
                ('trabajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='trabajos.trabajomanual')),
            ],
            options={
                'verbose_name': 'Foto de trabajo',
                'verbose_name_plural': 'Fotos de trabajo',
                'ordering': ['orden'],
            },
        ),
    ]
